### PR TITLE
Loop through env variables which works for multi-line var

### LINKED ISSUE #88: php-fpm conf is invalid if an env variable is multi-line
The error in the log is:

```
[31m !   Error deploying the application[0m
 !   → Your application has stopped unexpectedly with the following output:[0m

======== BEGIN OUTPUT ========[2m
2019-06-11 09:31:07.323588508 +0000 UTC [web-1] Optimizing defaults for M container...
2019-06-11 09:31:07.404506815 +0000 UTC [web-1] PHP Warning:  syntax error, unexpected $end, expecting TC_VARNAME in Unknown on line 500
2019-06-11 09:31:07.404556019 +0000 UTC [web-1] in /app/conf/autotune.php on line 25
2019-06-11 09:31:07.405318039 +0000 UTC [web-1] PHP Warning:  Invalid argument supplied for foreach() in /app/conf/autotune.php on line 29
2019-06-11 09:31:07.414110423 +0000 UTC [web-1] 4 processes at 196MB memory limit.
2019-06-11 09:31:07.504214654 +0000 UTC [web-1] PHP:  syntax error, unexpected $end, expecting TC_DOLLAR_CURLY or TC_QUOTED_STRING or '"' in Unknown on line 2
2019-06-11 09:31:07.504217272 +0000 UTC [web-1] [11-Jun-2019 09:31:07] ERROR: failed to load configuration file '/app/vendor/php/etc/php-fpm.conf'
2019-06-11 09:31:07.504369509 +0000 UTC [web-1] [11-Jun-2019 09:31:07] ERROR: FPM initialization failed
2019-06-11 09:31:07.510899162 +0000 UTC [web-1] Boot failed: php-fpm
[0m======== END OUTPUT ========[0m
```

### PR DESCRIPTION
**Pull request by EtienneM**
Fix #88

### CODE REVIEW

**Comment by Soulou** [comment]
It's actually not the right fix for this problem..

As what is generated in the php-fpm.conf is
```
env[SHLVL] = $SHLVL
env[APP_BUILD_TIME] = $APP_BUILD_TIME
env[PORT] = $PORT
env[ENV_VAR] = $ENV_VAR
```

So the content is not here. In your patch you're removing the new line to the variable name, which should be alright actually.

The problem is more

```
env | cut -f1 -d=
```

Of course in a multiline variable with JSON, this would get weird things as first column, not only the name of the var.

**Comment by EtienneM** [comment]
Yes I actually noticed... That's why I added back the `work in progress` label.

**Comment by EtienneM** [comment]
Works with https://my.scalingo.com/apps/579fd9e7fb0de600165ae4e6/deployments/187a5fd8-46f2-432f-b846-5318eadee2cd

**Comment by Soulou** [comment]
LGTM

**Pull request merged**
