### PR TITLE
[OPSB-238] Add ability to inject nginx configuration at the 'http' level of the config file

### PR DESCRIPTION
**Pull request by Soulou**

### CODE REVIEW

**Review by EtienneM — COMMENTED** [review]
Please join a documentation PR with this new feature

**Comment by Soulou** [comment]
https://github.com/Scalingo/documentation/pull/1177

**Comment by EtienneM** [comment]
I just noticed that the http level configuration is already implemented via the file servers.conf.erb according to our documentation (https://doc.scalingo.com/platform/deployment/buildpacks/nginx#configuration)

**Comment by Soulou** [comment]
> I just noticed that the http level configuration is already implemented via the file servers.conf.erb according to our documentation (https://doc.scalingo.com/platform/deployment/buildpacks/nginx#configuration)

It's only for the raw nginx buildpack, not PHP

**Comment by Soulou** [comment]
And PHP configuration is more difficult, we can't let a `servers.conf.erb` without plenty of helpers, that's why I've chosen this solution

**Review by EtienneM — APPROVED** [review]

**Pull request merged**
