### PR TITLE
After supporting phalcon module, support phalcon framework

### PR DESCRIPTION
**Pull request by Soulou**
https://sample-php-phalcon.scalingo.io

```
└> git push scalingo master
Enumerating objects: 27, done.
Counting objects: 100% (27/27), done.
Delta compression using up to 4 threads
Compressing objects: 100% (25/25), done.
Writing objects: 100% (27/27), 485.03 KiB | 3.88 MiB/s, done.
Total 27 (delta 0), reused 0 (delta 0)
 <-- Start deployment of sample-php-phalcon -->
       Fetching source code
-----> Cloning custom buildpack: https://github.com/Scalingo/php-buildpack#feature/phalcon-framework
-----> Bundling NGINX 1.15.8
-----> Bundling PHP 7.2.15
-----> Bundling extensions
       apcu
       phpredis
       mongodb
       mcrypt
-----> Vendoring Composer
       Updating Composer
-----> Bundling additional extensions phalcon
       phalcon
Updating to version 1.8.4 (stable channel).
   Downloading (100%)
Use composer self-update --rollback to return to version 1.6.5
-----> Installing application dependencies with Composer
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
-----> Detected Phalcon app
-----> Setting up Phalcon app
-----> Vendoring binaries into slug
 Build complete, shipping your container...
 Waiting for your application to boot... 
 <-- https://sample-php-phalcon.scalingo.io -->
```

### CODE REVIEW

**Comment by EtienneM** [comment]
All our samples follow the same graphical template. Can you update your sample to follow it? Or was it just a test app you will remove?

**Comment by EtienneM** [comment]
And you can also add it to https://doc.scalingo.com/samples

**Comment by Soulou** [comment]
It's a test app, but I'll transform it into a sample changing the default theme

**Comment by yannski** [comment]
@Soulou can you add a changelog entry as well?

**Comment by Soulou** [comment]
Once the sample will be ready

**Pull request merged**
